version: "2"
checks:
  argument-count:
    config:
      threshold: 6
  file-lines:
    config:
      threshold: 512
  method-lines:
    config:
      threshold: 32
exclude_patterns:
  - "__tests__/"
  - "__mocks__/"
  - "openshift/"
  - "doc/"
  - "**/node_modules/"
  - "script/"
  - "**/vendor/"
  - "**/*.d.ts"
