# Copyright 2021 The Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Repomountie application.
  name: repomountie
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: repomountie-config
      labels:
        app: repomountie
    data:
      config.json: |
        {
          "sso": {
            "authUrl": "https://oidc.gov.bc.ca/auth/realms/devhub/protocol/openid-connect/auth",
            "tokenUrl": "https://oidc.gov.bc.ca/auth/realms/devhub/protocol/openid-connect/token",
            "certsUrl": "https://oidc.gov.bc.ca/auth/realms/devhub/protocol/openid-connect/certs"
          },
          "staleIssueMaxDaysOld": 120
        }
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: repomountie
        component: bot
      name: bot-env
    data:
      APP_ID: ${APP_ID}
      LOG_LEVEL: debug
      PORT: "8080"
      NODE_ENV: production
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: repomountie
      name: github-creds
    stringData:
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      PRIVATE_KEY: ${PRIVATE_KEY}
    type: Opaque
  - apiVersion: v1
    kind: Route
    metadata:
      name: repomountie
      labels:
        app: repomountie
    spec:
      path: ""
      port:
        targetPort: https
      tls:
        termination: edge
      to:
        kind: Service
        name: repomountie
        weight: 100
  - apiVersion: v1
    # Using the kind `DeploymentConfig` will allow a deployment to trigger
    # based on an image change event. Not supported with kind `Deployment`.
    kind: DeploymentConfig
    metadata:
      name: repomountie
      labels:
        app: repomountie
    spec:
      replicas: 1
      revisionHistoryLimit: 3
      selector:
        app: repomountie
        component: bot
      template:
        metadata:
          labels:
            app: repomountie
            component: bot
        spec:
          terminationGracePeriodSeconds: 15
          containers:
            - name: bot
              ports:
                - containerPort: 8080
              envFrom:
                - secretRef:
                    name: github-creds
                - configMapRef:
                    name: bot-env
              resources:
                limits:
                  cpu: 500m
                  memory: 320Mi
                requests:
                  cpu: 500m
                  memory: 192Mi
              volumeMounts:
                - name: config-vol
                  mountPath: /opt/app-root/src/build/config/config.json
                  subPath: config.json
          volumes:
            - name: config-vol
              configMap:
                name: repomountie-config
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - bot
            from:
              kind: ImageStreamTag
              name: "repomountie:${REPOMOUNTIE_IMAGE_TAG}"
              namespace: 85d4e0-tools
        - type: ConfigChange
  - apiVersion: v1
    kind: Service
    metadata:
      name: repomountie
      labels:
        app: repomountie
    spec:
      selector:
        app: repomountie
      ports:
        - name: https
          port: 443
          targetPort: 8080
parameters:
  - name: APP_ID
    description: |
      This application ID is provided by GitHub. Its required by the bot
      to correctly integrate with GitHub.
    required: true
  - name: WEBHOOK_SECRET
    description: |
      This is the secret used by GitHub when sending a web-hook payload
      to the bot.
    from: "[a-zA-Z0-9]{32}"
    generate: expression
    required: true
  - name: PRIVATE_KEY
    description: |
      This is the GitHub App private PGP key generated and provided by
      GitHub when creating the application.
    required: true
  - name: REPOMOUNTIE_IMAGE_TAG
    description: |
      The tag used to deploy the repomountie component.
    required: true
  - name: NAMESPACE
    description: |
      The namespace where the components are being deployed
      and the associated NSP could be created.
    required: true
