apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-cicd
  labels:
    app: github-cicd
---
kind: Role
apiVersion: authorization.openshift.io/v1
metadata:
  name: github-cicd
  labels:
    app: github-cicd
rules:
  - apiGroups:
      - build.openshift.io
      - ""
    resources:
      - buildconfigs/instantiate
    verbs:
      - create
  - apiGroups:
      - build.openshift.io
      - ""
    resources:
      - buildconfigs
      - builds
    verbs:
      - create
      - get
      - list
  - apiGroups:
      - image.openshift.io
      - ""
    resources:
      - imagestreamimages
      - imagestreamtags
    verbs:
      - create
      - get
      - list
  - apiGroups:
      - image.openshift.io
      - ""
    resources:
      - imagestreams
    verbs:
      - get
      - list
  - apiGroups:
      - build.openshift.io
      - ""
    resources:
      - builds/log
    verbs:
      - get
      - list
      - watch
---
kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: github-cicd
  labels:
    app: github-cicd
subjects:
  - kind: ServiceAccount
    name: github-cicd
roleRef:
  kind: Role
  name: github-cicd
  namespace: devhub-tools
  apiGroup: authorization.openshift.io
